version: '3.8'

services:
  web:
    build: 
      context: .
      target: development
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=migrations.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=${SECRET_KEY:-default-secret-key}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - RATELIMIT_STORAGE_URL=memory://
      - PORT=5000
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0 --port 5000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5001
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - web 